services:
  cropwise-api-backend:
    build:
      context: ./api_backend
      dockerfile: Dockerfile
    container_name: cropwise-api-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    volumes:
      - ./api_backend/:/app
    # restart: unless-stopped
