services:
  cropwise-api-backend:
    build:
      context: ./api_backend
      dockerfile: Dockerfile
    container_name: cropwise-api-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    volumes:
      - ./api_backend/:/app
    # restart: unless-stopped

  cropwise-iot-backend:
    build:
      context: ./iot_backend
      dockerfile: Dockerfile
    container_name: cropwise-iot-backend
    ports:
      - "9000:9000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    volumes:
      - ./iot_backend/:/app
    # restart: unless-stopped
